name: Automated Training [Workflow - 10]

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  training_workloads:
    name: Training Workloads [ Stock Datas ]
    runs-on: ubuntu-latest
    environment: Production

    strategy:
      matrix:
        python-version: [3.11]

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      DATASET_NAME: indonesia_stocks
      MODEL_REGISTRY_NAME: stock_models_10
      HF_USERNAME: qywok

    steps:
      - name: Set Global Directory
        run: git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3     
        with:
          lfs: true
          persist-credentials: false
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cloning Model from Hugging Face
        id: cloning_model
        run: |
          git clone https://huggingface.co/qywok/stock_models_10

      - name: Cloning Datasets From Hugging Face
        id: cloning_dataset
        run: git clone https://huggingface.co/datasets/$HF_USERNAME/$DATASET_NAME

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/linux/ubuntu.production.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Requirements Install
        id: requirements_install
        run: |
          pip install -r requirements/linux/ubuntu.production.txt
          pip install torch==2.7.0 --index-url https://download.pytorch.org/whl/cpu 

      - name: test workloads
        run: ls -al $DATASET_NAME/workloads

      - name: test training
        run: |
          python autotraining.py \
            --workloads_json=workloads_10.json \
            --model_registry=stock_models_10

      - name: test models registry
        run: ls -al stock_models_10

      - name: Ingest to Hugging Face Models
        run: |
          cd stock_models_10
          git config --local user.email "alfariqyraihan@gmail.com"
          git config --local user.name "qywok"
          git add -A 
          git diff-index --quiet HEAD || git commit -m "[ Ingest Model ]"
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/$HF_USERNAME/$MODEL_REGISTRY_NAME main --force
          cd .. && ls -al